### ISSUE TITLE
Suggest templates for issues and pull requests

### ISSUE THREAD

**Issue by krvoigt** [OCR-D/zenhub#41] opened 2022-02-02 09:21 UTC
Please suggest templates for issues und pr. Ask for feedback and implement them in github.

**Comment by mweidling** [comment] 2022-02-02 12:37
Here comes a first draft for issue templates.

---

## Bug

### I expected the following to happen:

A brief description of what went wrong.

### What happened instead:

A brief description of the expected behavior.

### OCR-D version

---

## Feature

### Description

What do you want us to implement?

### Use case(s)

What is this new feature useful for?

---

@kba You said that you tried templates in core before. What did they look like? What are the reasons you tossed them?

**Comment by krvoigt** [comment] 2022-02-07 09:51
@mweidling Please add user stories ro the template with ah short description how stories should look like.

**Comment by krvoigt** [comment] 2022-02-07 09:54
maybe we can differenciate between required and optional. For us internally Acceptance Criteria would help.

**Comment by mweidling** [comment] 2022-02-23 13:40
@krvoigt The description of this ticket is a bit fuzzy: Which repo should I add these templates to?

**Comment by mweidling** [comment] 2022-02-23 14:27
See https://github.com/OCR-D/zenhub/commit/f6dce6f699b29b8073e97f10bf87e122ba8104e2.

**Comment by kba** [comment] 2022-03-01 11:08
> See [f6dce6f](https://github.com/OCR-D/zenhub/commit/f6dce6f699b29b8073e97f10bf87e122ba8104e2).

Thanks @mweidling I added some comments.

**Comment by kba** [comment] 2022-03-01 11:37
> And a first draft for PRs...
> 
> ## Pull request
> ### Description
> Provide a brief summary of what you did.
> 
> ### Tests
> How can the functionality/fix provided by this PR be tested?
> 
> ### Ticket reference
> Which ticket(s) does this PR belong to (if applicable)?

Maybe we should also re-enable code coverage tests. For example for https://github.com/OCR-D/core/pull/800 I would feel much more content if I was sure that all the changes are covered by tests . Being forced to make sure of that is the obvious downside :)

**Comment by mweidling** [comment] 2022-03-02 11:49
Thanks @kba, I added your feedback over at ddd4135ea2052335ef8b6b8927fe3a565f53e049.

What do you mean by "**re-enabling** code coverage tests"? Do you mean asking for them?

**Comment by kba** [comment] 2022-03-02 12:19
> What do you mean by "**re-enabling** code coverage tests"? Do you mean asking for them?

We had set up codecov.io for OCR-D/core and we do have a `make coverage` target to measure coverage of our unit tests. But we neglected this for a long time because increasing test coverage, while valuable for sustainability, is very time-consuming and offers little gain. It could be a good way to get to know the codebase for anyone new-ish to the project 👀 :-)

**Comment by mweidling** [comment] 2022-03-02 12:57
> But we neglected this for a long time because increasing test coverage, while valuable for sustainability, is very time-consuming and offers little gain.

But don't you think that code coverage (which is connected with unit tests) could be valuable for any further development? If so, I'd add it to the PR template.

**Comment by kba** [comment] 2022-03-02 17:51
> But don't you think that code coverage

Absolutely, I am just hesitant because it means an additional hurdle to get a PR merged.

**Comment by mweidling** [comment] 2022-03-03 11:57
> Absolutely, I am just hesitant because it means an additional hurdle to get a PR merged.

Sure, code quality is always a bit of work :) But since it's worth the effort, let's give it a shot.

**Comment by mweidling** [comment] 2022-03-03 12:03
Should these templates be added to orcd_all/core as well?

**Comment by krvoigt** [comment] 2022-03-03 13:56
I think the feature description we only need in zenhub, because it is always on epic level. Bugs and pr do we need in core and maybe other repositories too? What do you think @kba ?

**Closed** 2022-04-06 11:22 UTC
